const urls = {
  REACT_APP_API_URL_TIME_CHECK: process.env.REACT_APP_API_URL_TIME_CHECK,
  REACT_APP_API_URL: process.env.REACT_APP_API_URL,
  REACT_APP_API_URL_LEAVE_TIME_BENEFIT:
    process.env.REACT_APP_API_URL_LEAVE_TIME_BENEFIT,
  REACT_APP_API_URL_TIME_LOG: process.env.REACT_APP_API_URL_TIME_LOG,
  REACT_APP_API_URL_SYNC_LOG: process.env.REACT_APP_API_URL_SYNC_LOG,
  REACT_APP_API_URL_MENU: process.env.REACT_APP_API_URL_MENU,
  REACT_APP_API_TIMESHEET: process.env.REACT_APP_API_TIMESHEET,
  REACT_APP_API_CORE: process.env.REACT_APP_API_CORE,
};

export default urls;
